# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59c686a8f055468a1cc8b47f508d893580de57b0ad170e4955374ab189c87ff8149094ecc26d7d353abb5cf700a33372220caf26684a4186d3fa68c78244abf

test:
  secret_key_base: 592da959a64d678e7359b68ffbf2a43fd128edcdac94fa48fbc25199cdd2b91772924d4fdb311ee2350faa7e00411e5fae2f26c65774bb118fb08484cca1b414

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
