# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96cd5045148be7728dc3f3f1d2bd850bcd7a70e433554ca11f93a798e362e796fbf74ff9c82ef476bfe7ea6764d7f98ef5ff3deff8cb850ff001d8598b1bbc2

test:
  secret_key_base: 42a7b58e3c49615deea4896b075c215cf76746dca5b51acdcc2d447f8487c371bde0dee8c7d7d7bd3f0b1649e957e50ae5a31a13b7d5bc51780a6d17c217bbe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
